In [7]:
from pathlib import Path
import pandas as pdb
import numpy as np
from modules import calculations

In [8]:


attendance_df = calculations.read_file_by_extension(open('../data/1_(2月)考勤报表_mock.xls', 'rb'))
abnormal_df = calculations.preprocess_abnormal_stats(calculations.read_file_by_extension(open('../data/1_(2月)異常考勤統計表.xls', 'rb')))
report_df = calculations.read_file_by_extension(open('../data/加班報表.tsv', 'rb'))
parsed_attendances = calculations.parse_attendance_report(attendance_df)
parsed_abnormal = calculations.parse_abnormal_stats(abnormal_df)
parsed_report = calculations.parse_overtime_leave_report(report_df)
print('Employees:', parsed_attendances['Employee'].unique())
summary = calculations.generate_employee_summary('陳昭穎', parsed_attendances, parsed_abnormal, parsed_report)
print(summary['Monthly Report'])
print(summary['Duty Time Entries'].head())

Employees: ['陳昭穎' '陳建中' '右中' '右無' '右小' '左食' '左中' '左無' '左小']
Index(['Type', 'Date', 'Start Time', 'End Time', 'Elapsed Minutes',
       'OT Attribute', 'Patient/Note', 'Employee', 'Period', 'Leave Type',
       'Reason', 'Patient Name', 'Total Duration (hr)'],
      dtype='object')



emp_report
       Type        Date  Start Time     End Time  Elapsed Minutes  \
0  Overtime  2026-02-06  上午 8:20:00  下午 12:50:00            270.0
1     Leave  2026-02-09         NaN          NaN              NaN
2  Overtime  2026-02-10  上午 8:30:00  下午 12:50:00            260.0
3     Leave  2026-02-18         NaN          NaN              NaN
4     Visit  2026-02-12  下午 1:30:00   下午 4:20:00              NaN

  OT Attribute Patient/Note Employee Period Leave Type Reason Patient Name  \
0          煮水藥          707      陳昭穎    NaN        NaN    NaN          NaN
1          NaN          NaN      陳昭穎     早診         特休     睡覺          NaN
2         病人拔針           阿寶      陳昭穎    NaN        NaN    NaN          NaN
3          NaN          NaN      陳昭穎     早診         病假    看牙齒          NaN
4          NaN          NaN      陳昭穎    NaN        NaN    NaN        婷婷、娟娟

   Total Duration (hr)
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4             2.833333
     Month  Total Late Mins  Total Overtime Mins  Total On-Duty Hours  \
0  2026-02             88.0                740.0               241.12

   Total Leave Hours
0                  8
         Date Period Start Time End Time  Total Duration (hr)  \
0  2026-02-01     早診      07:52    12:02                 4.17
1  2026-02-01     午診      16:02    20:07                 4.08
2  2026-02-02     早診      07:56    12:06                 4.17
3  2026-02-02     午診      16:02    20:03                 4.02
4  2026-02-03     早診      07:52    12:10                 4.30

   Overtime Duration (min)  Late Duration (min)
0                      0.0                  0.0
1                      0.0                  0.0
2                      0.0                  0.0
3                      0.0                  0.0
4                      0.0                  0.0

In [9]:
parsed_attendances

,Employee,Date,Period,Start Time,End Time,Total Duration (hr),Total Duration (min)
0,陳昭穎,2026-02-01,早診,07:52,12:02,4.17,250.0
1,陳昭穎,2026-02-01,晚診,16:02,20:07,4.08,245.0
2,陳昭穎,2026-02-02,早診,07:56,12:06,4.17,250.0
3,陳昭穎,2026-02-02,晚診,16:02,20:03,4.02,241.0
4,陳昭穎,2026-02-03,早診,07:52,12:10,4.30,258.0
...,...,...,...,...,...,...,...
533,左小,2026-02-28,晚診,16:05,20:04,3.98,239.0
534,左小,2026-02-29,早診,08:00,12:07,4.12,247.0
535,左小,2026-02-29,晚診,15:52,20:05,4.22,253.0
536,左小,2026-02-30,早診,08:05,12:07,4.03,242.0
537,左小,2026-02-30,晚診,15:55,20:00,4.08,245.0

In [10]:
parsed_attendances['Employee']

0      陳昭穎
1      陳昭穎
2      陳昭穎
3      陳昭穎
4      陳昭穎
      ...
533     左小
534     左小
535     左小
536     左小
537     左小
Name: Employee, Length: 538, dtype: object

In [11]:
summary = calculations.generate_employee_summary("陳昭穎", parsed_attendances, parsed_abnormal, parsed_report)

Index(['Type', 'Date', 'Start Time', 'End Time', 'Elapsed Minutes',
       'OT Attribute', 'Patient/Note', 'Employee', 'Period', 'Leave Type',
       'Reason', 'Patient Name', 'Total Duration (hr)'],
      dtype='object')



emp_report
       Type        Date  Start Time     End Time  Elapsed Minutes  \
0  Overtime  2026-02-06  上午 8:20:00  下午 12:50:00            270.0
1     Leave  2026-02-09         NaN          NaN              NaN
2  Overtime  2026-02-10  上午 8:30:00  下午 12:50:00            260.0
3     Leave  2026-02-18         NaN          NaN              NaN
4     Visit  2026-02-12  下午 1:30:00   下午 4:20:00              NaN

  OT Attribute Patient/Note Employee Period Leave Type Reason Patient Name  \
0          煮水藥          707      陳昭穎    NaN        NaN    NaN          NaN
1          NaN          NaN      陳昭穎     早診         特休     睡覺          NaN
2         病人拔針           阿寶      陳昭穎    NaN        NaN    NaN          NaN
3          NaN          NaN      陳昭穎     早診         病假    看牙齒          NaN
4          NaN          NaN      陳昭穎    NaN        NaN    NaN        婷婷、娟娟

   Total Duration (hr)
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4             2.833333

In [13]:
summary.keys()

dict_keys(['Monthly Report', 'Overtime Detail', 'Leave Details', 'Duty Time Entries', 'Visit Entries', 'Visit Weekly Summary'])

In [14]:
summary["Duty Time Entries"].head()

,Date,Period,Start Time,End Time,Total Duration (hr),Overtime Duration (min),Late Duration (min)
0,2026-02-01,早診,07:52,12:02,4.17,0.0,0.0
1,2026-02-01,午診,16:02,20:07,4.08,0.0,0.0
2,2026-02-02,早診,07:56,12:06,4.17,0.0,0.0
3,2026-02-02,午診,16:02,20:03,4.02,0.0,0.0
4,2026-02-03,早診,07:52,12:10,4.30,0.0,0.0

In [15]:
summary["Overtime Detail"].head()

,Date,Start Time,End Time,Elapsed Minutes,OT Attribute,Patient/Note
0,2026-02-06,上午 8:20:00,下午 12:50:00,270.0,煮水藥,707
2,2026-02-10,上午 8:30:00,下午 12:50:00,260.0,病人拔針,阿寶
5,2026-02-19,上午 10:30:00,下午 2:00:00,210.0,煮水藥,505

In [3]:
report_df = calculations.read_file_by_extension(open('../data/加班報表.tsv', 'rb'))
parsed_report = calculations.parse_overtime_leave_report(report_df)
parsed_report.head()

,Type,Date,Start Time,End Time,Elapsed Minutes,OT Attribute,Patient/Note,Employee,Period,Leave Type,Reason,Patient Name,Total Duration (hr)
0,Overtime,2026/2/6,上午 8:20:00,下午 12:50:00,270.0,煮水藥,707,陳昭穎,NaN,NaN,NaN,NaN,NaN
1,Leave,2026/2/9,NaN,NaN,NaN,NaN,NaN,陳昭穎,早診,特休,睡覺,NaN,NaN
2,Overtime,2026/2/10,上午 8:30:00,下午 12:50:00,260.0,病人拔針,阿寶,陳昭穎,NaN,NaN,NaN,NaN,NaN
3,Leave,2026/2/18,NaN,NaN,NaN,NaN,NaN,陳昭穎,早診,病假,看牙齒,NaN,NaN
4,Visit,2026/2/12,下午 1:30:00,下午 4:20:00,NaN,NaN,NaN,陳昭穎,NaN,NaN,NaN,婷婷、娟娟,2.833333

In [6]:
report_df = calculations.read_file_by_extension(open('../data/上班時數表單 (回覆).xlsx', 'rb'))
parsed_report = calculations.parse_overtime_leave_report(report_df)
parsed_report.head()

,Type,Date,Period,Leave Type,Reason,Employee,Start Time,End Time,Patient Name,Total Duration (hr)
0,Leave,2026-02-24 00:00:00,晚診,病假,看牙齒,陳昭穎,NaN,NaN,NaN,NaN
1,Visit,2026-02-09 00:00:00,NaN,NaN,NaN,陳昭穎,13:00:00,15:00:00,陳中白,2.0
2,Leave,2026-02-27 00:00:00,早診,病假,生病,陳昭穎,NaN,NaN,NaN,NaN